version: 2
jobs:
  build:
    docker:
      - image: node:7.4.0
    working_directory: ~/code-craftsmanship-organization/continuous-integration-with-jenkins-travis-and-circleci
    dependencies:
      pre:
        - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
        - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
        - sudo apt-get update
        - sudo apt-get install rethinkdb=2.3\*
    steps:
      - checkout
      - run:
          name: Pre-Dependencies
          command: mkdir -p /Users/marcelbelmont/code-craftsmanship-organization/continuous-integration-with-jenkins-travis-and-circleci/artifacts\
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: NPM Test
          command: npm test
      - store_artifacts:
          path: ~/code-craftsmanship-organization/continuous-integration-with-jenkins-travis-and-circleci/.circleci/config.yml/artifacts
      - add_ssh_keys
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # Install Heroku fingerprint
              mkdir -p ~/.ssh
              echo 'heroku.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAu8erSx6jh+8ztsfHwkNeFr/SZaSOcvoa8AyMpaerGIPZDB2TKNgNkMSYTLYGDK2ivsqXopo2W7dpQRBIVF80q9mNXy5tbt1WE04gbOBB26Wn2hF4bk3Tu+BNMFbvMjPbkVlC2hcFuQJdH4T2i/dtauyTpJbD/6ExHR9XYVhdhdMs0JsjP/Q5FNoWh2ff9YbZVpDQSTPvusUp4liLjPfa/i0t+2LpNCeWy8Y+V9gUlDWiyYwrfMVI0UwNCZZKHs1Unpc11/4HLitQRtvuk0Ot5qwwBxbmtvCDKZvj1aFBid71/mYdGRPYZMIxq1zgP1acePC1zfTG/lvuQ7d0Pe0kaw==' >> ~/.ssh/known_hosts

              git config --global push.default simple
              git push -f git.heroku.com/morning-beach-35447.git
            fi
